// Code generated by argsgen.
// DO NOT EDIT!
package main

import (
    "flag"
    "os"
)

func (o *options) Parse() error {
    flagSet := flag.NewFlagSet(os.Args[0], flag.ExitOnError)
    flagSet.StringVar(&o.db, "db", o.db, "database name")
    flagSet.StringVar(&o.out, "out", o.out, "output file")
    flagSet.StringVar(&o.compressor, "compressor", o.compressor, "compression algorithm")

    var positional []string
    args := os.Args[1:]
    for len(args) > 0 {
        if err := flagSet.Parse(args); err != nil {
            return err
        }

        if remaining := flagSet.NArg(); remaining > 0 {
            posIndex := len(args) - remaining
            positional = append(positional, args[posIndex])
            args = args[posIndex+1:]
            continue
        }
        break
    }

    return nil
}

func (o *options) MustParse() {
    if err := o.Parse(); err != nil {
        panic(err)
    }
}
